# See: https://circleci.com/docs/2.0/language-python/

version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.8.5-buster

    steps:
      - checkout

      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip wheel setuptools
            pip install -r requirements.txt -r site/requirements.txt

      - run:
          name: Build site
          command: |
            source venv/bin/activate
            # n = nitpicky (broken links), W = warnings as errors,
            # T = full tracebacks, keep-going = run to completion even with errors
            make -C site/ SPHINXOPTS="-nWT --keep-going" html

      - store_artifacts:
          path: site/_build/html
